const demoNote = 'Conteúdo de demonstração — sujeito a confirmação.';
const instagramUrl = '';

const activities = [
  { number: '01', title: 'Artes plásticas', copy: 'Experimentar materiais, cores, formas e ideias.', tone: 'pink', icon: '✳' },
  { number: '02', title: 'Teatro', copy: 'Criar personagens, histórias e novas formas de expressão.', tone: 'lavender', icon: '◒' },
  { number: '03', title: 'Música', copy: 'Explorar sons, ritmos e movimento.', tone: 'yellow', icon: '♫' },
  { number: '04', title: 'Movimento e dança', copy: 'Descobrir o corpo através do movimento e da brincadeira.', tone: 'mint', icon: '〰' },
  { number: '05', title: 'Literatura e conto', copy: 'Entrar em histórias e deixar a imaginação viajar.', tone: 'blue', icon: '❋' },
];
const ages = [
  ['0–2', 'Primeiros contactos com a criatividade, o movimento e a descoberta.'],
  ['3–5', 'Experiências pensadas para brincar, criar e experimentar.'],
  ['6–9', 'Mais espaço para explorar técnicas, ideias e expressão.'],
  ['10–12', 'Desafios criativos que estimulam autonomia e imaginação.'],
  ['Famílias', 'Momentos para criar e viver experiências em conjunto.'],
];
const experiences = [
  { title: 'Oficina de Pintura Sensorial', copy: 'Uma experiência para explorar cores, texturas e diferentes formas de criar.', age: '3–5 anos', date: 'Data a confirmar', duration: 'Duração demo', image: './assets/pintura-ao-ar-livre.png', alt: 'Atividade de pintura ao ar livre partilhada pela marca' },
  { title: 'Movimento & Imaginação', copy: 'Uma oficina onde o corpo também conta histórias.', age: '6–9 anos', date: 'Data a confirmar', duration: 'Duração demo', image: './assets/brincadeira-em-grupo.png', alt: 'Brincadeira de grupo no exterior partilhada pela marca' },
  { title: 'Pequenos Contadores de Histórias', copy: 'Uma viagem pela imaginação através de histórias e personagens.', age: 'Famílias', date: 'Data a confirmar', duration: 'Duração demo', image: './assets/oficina-desenho.png', alt: 'Crianças a desenhar em conjunto numa mesa' },
];
const gallery = [
  { className: 'gallery-tall', label: 'Crianças a desenhar juntas à volta de uma mesa', image: './assets/oficina-desenho.png' },
  { className: 'gallery-wide', label: 'Mãos a preparar uma atividade de cozinha em grupo', image: './assets/oficina-cozinha.png' },
  { className: 'gallery-small', label: 'Camião dos Bombeiros de Pernes durante uma visita de grupo', image: './assets/visita-bombeiros.png' },
  { className: 'gallery-medium', label: 'Criança a pintar ao ar livre', image: './assets/pintura-ao-ar-livre.png' },
  { className: 'gallery-small gallery-last', label: 'Grupo de crianças a brincar em conjunto no exterior', image: './assets/brincadeira-em-grupo.png' },
];

const arrow = '<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M3 10h13M10 4l6 6-6 6" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const logo = `<a class="brand" href="#inicio" aria-label="Mini Artistas à Solta — início"><img class="brand-logo" src="./assets/logo-mini-artistas.svg" alt="" /><span class="brand-wordmark">Oficinas criativas<br><b>para crianças e famílias</b></span></a>`;
const imagePlaceholder = (label, tone, art = 'abstract') => `<div class="art-placeholder ${tone} art-${art}" role="img" aria-label="${label}"><span class="art-caption">${label}</span><span class="art-sun" aria-hidden="true"></span><span class="art-shape" aria-hidden="true"></span><span class="art-line" aria-hidden="true"></span><span class="art-dot" aria-hidden="true"></span><span class="art-stem" aria-hidden="true"></span></div>`;
const photo = (src, alt, className = '') => `<div class="real-photo ${className}"><img src="${src}" alt="${alt}" loading="${className.includes('hero-photo') ? 'eager' : 'lazy'}" ${className.includes('hero-photo') ? 'fetchpriority="high"' : ''} /><span class="photo-grain" aria-hidden="true"></span></div>`;
const instagramLink = (className) => instagramUrl
  ? `<a class="${className}" href="${instagramUrl}" target="_blank" rel="noreferrer">Instagram <span>↗</span></a>`
  : `<span class="${className} instagram-placeholder" aria-label="Instagram — link oficial a inserir">Instagram <span>↗</span></span>`;

function Navbar() { return `<header class="site-header"><nav class="nav-shell" aria-label="Navegação principal">${logo}<div class="nav-links" id="nav-links"><a href="#inicio">Início</a><a href="#atividades">Atividades</a><a href="#sobre">Sobre</a><a href="#galeria">Galeria</a><a href="#contactos">Contactos</a></div><a class="button button-small nav-cta" href="#experiencias">Ver atividades ${arrow}</a><button class="menu-toggle" type="button" aria-label="Abrir menu" aria-expanded="false" aria-controls="nav-links"><span></span><span></span></button></nav></header>`; }
function Hero() { return `<section class="hero section-wrap" id="inicio"><div class="hero-copy"><p class="eyebrow"><span class="eyebrow-dot"></span> Oficinas criativas · Santarém</p><h1>Pequenos artistas,<br><em>grandes descobertas.</em></h1><p class="hero-intro">Oficinas criativas para crianças e famílias, onde brincar, criar e experimentar fazem parte da mesma aventura.</p><div class="hero-actions"><a class="button" href="#experiencias">Ver próximas atividades ${arrow}</a><a class="text-link" href="#sobre">Conhecer a Mini Artistas <span>↗</span></a></div><p class="hero-location"><span aria-hidden="true">⌖</span> São Vicente do Paul <i>·</i> Santarém</p><span class="hero-scribble" aria-hidden="true">✳</span></div><div class="hero-visual">${photo('./assets/brincadeira-em-grupo.png', 'Crianças a brincar e a descobrir em grupo no exterior', 'hero-photo')}<span class="hero-sticker">criar<br>é descobrir <b>♡</b></span><span class="hero-side-note">brincar · criar · crescer <i>↗</i></span></div><div class="hero-bottom-note">UM ESPAÇO PARA CRESCER A CRIAR <span>✳</span></div></section>`; }
function ActivityCategories() { return `<section class="section activities-section" id="atividades"><div class="section-wrap"><div class="section-heading split-heading"><div><p class="eyebrow">Curiosidade em movimento</p><h2>Um espaço para criar,<br><em>brincar e descobrir</em></h2></div><p class="section-lead">A Mini Artistas à Solta cria oficinas e experiências artísticas para crianças e famílias, juntando criatividade, movimento, imaginação e descoberta.</p></div><div class="activity-grid">${activities.map((a) => `<article class="activity-card ${a.tone}"><span class="activity-number">${a.number}</span><span class="activity-icon" aria-hidden="true">${a.icon}</span><h3>${a.title}</h3><p>${a.copy}</p><span class="card-arrow" aria-hidden="true">↗</span></article>`).join('')}</div><p class="demo-caption">${demoNote} As áreas de atividade são exemplos editáveis.</p></div></section>`; }
function AgeGroups() { return `<section class="section ages-section"><div class="section-wrap age-layout"><div class="age-heading"><p class="eyebrow">Para crescer ao seu ritmo</p><h2>Cada idade,<br>uma forma diferente<br><em>de descobrir.</em></h2><span class="age-doodle" aria-hidden="true">✳</span></div><div class="age-list">${ages.map(([age, text], index) => `<article class="age-row"><span class="age-index">0${index + 1}</span><h3>${age}${age !== 'Famílias' ? ' anos' : ''}</h3><p>${text}</p><span class="age-mark" aria-hidden="true">↗</span></article>`).join('')}<p class="demo-caption">${demoNote} Faixas etárias de demonstração.</p></div></div></section>`; }
function UpcomingActivities() { return `<section class="section experiences-section" id="experiencias"><div class="section-wrap"><div class="section-heading experiences-heading"><div><p class="eyebrow">Um convite à descoberta</p><h2>Há sempre algo novo<br><em>para descobrir</em></h2></div><a class="text-link desktop-link" href="#contactos">Quero saber mais <span>↗</span></a></div><p class="demo-caption experience-note">Atividades e datas de demonstração — conteúdo editável a confirmar.</p><div class="experience-grid">${experiences.map((item) => `<article class="experience-card"><div class="experience-image">${photo(item.image, item.alt)}<span class="demo-tag">DEMO</span></div><div class="experience-content"><p class="experience-meta">${item.age} <span>·</span> ${item.date}</p><h3>${item.title}</h3><p>${item.copy}</p><div class="experience-foot"><span>${item.duration}<br><small>São Vicente do Paul</small></span><a href="#contactos" aria-label="Saber mais sobre ${item.title}">Saber mais ${arrow}</a></div></div></article>`).join('')}</div><a class="button button-outline all-activities" href="#contactos">Ver todas as atividades ${arrow}</a></div></section>`; }
function WhyCreate() { const values = [['01','Imaginar','Dar espaço ao que ainda não existe.'],['02','Experimentar','Descobrir fazendo, tentando, mudando.'],['03','Expressar','Encontrar muitas maneiras de dizer.'],['04','Descobrir','Levar connosco novas possibilidades.']]; return `<section class="section why-section"><div class="section-wrap why-layout"><div class="why-intro"><p class="eyebrow">Mais do que fazer</p><h2>Porque criar<br>também é <em>crescer.</em></h2><p>Cada experiência pode ser uma oportunidade para experimentar, imaginar, expressar e descobrir algo novo.</p><span class="why-star" aria-hidden="true">✳</span></div><div class="values-list">${values.map(([n, title, copy]) => `<article class="value-row"><span>${n}</span><h3>${title}</h3><p>${copy}</p><b aria-hidden="true">↗</b></article>`).join('')}</div></div></section>`; }
function Gallery() { return `<section class="section gallery-section" id="galeria"><div class="section-wrap"><div class="section-heading gallery-heading"><div><p class="eyebrow">Pequenos momentos, grandes memórias</p><h2>Momentos <em>que ficam</em></h2></div><p class="handwritten">criar juntos <span>✦</span></p></div><div class="gallery-grid">${gallery.map((item) => `<div class="gallery-item ${item.className}">${photo(item.image, item.label)}</div>`).join('')}<span class="gallery-note gallery-note-one">pequenos momentos</span><span class="gallery-note gallery-note-two">mãos ocupadas,<br>imaginação à solta</span></div><p class="demo-caption">Momentos partilhados pela Mini Artistas à Solta no Instagram.</p></div></section>`; }
function About() { return `<section class="section about-section" id="sobre"><div class="section-wrap about-layout"><div class="about-visual">${photo('./assets/oficina-desenho.png', 'Crianças a desenhar juntas em redor de uma mesa', 'about-photo')}<span class="about-label">um lugar para ser<br>e acontecer</span></div><div class="about-copy"><p class="eyebrow">Um projeto feito de encontros</p><h2>Um espaço de criação,<br><em>expressão e liberdade.</em></h2><p>Aqui, a criatividade é uma forma de brincar, experimentar e estar em relação. As oficinas juntam diferentes linguagens artísticas para criar experiências significativas para crianças e famílias.</p><a class="text-link" href="#contactos">Saber mais sobre nós <span>↗</span></a><span class="about-flower" aria-hidden="true">✳</span></div></div></section>`; }
function Location() { return `<section class="location-band"><div class="section-wrap location-layout"><div><p class="eyebrow">Um ponto de encontro</p><h2>Estamos em <em>Santarém.</em></h2></div><div class="location-card"><span class="location-pin" aria-hidden="true">⌖</span><div><strong>São Vicente do Paul</strong><p>Santarém, Portugal</p></div><span class="location-orbit" aria-hidden="true">✳</span></div></div></section>`; }
function InterestForm() { return `<section class="section contact-section" id="contactos"><div class="section-wrap contact-layout"><div class="contact-copy"><p class="eyebrow">O próximo passo começa aqui</p><h2>Quero saber <em>mais.</em></h2><p>Quer saber mais sobre as próximas oficinas e experiências da Mini Artistas à Solta?</p><div class="contact-aside"><span aria-hidden="true">✳</span><p>Uma pergunta, uma ideia,<br>uma vontade de criar.</p></div></div><form class="interest-form" id="interest-form"><div class="form-row"><label>Nome<input name="name" type="text" placeholder="O seu nome" autocomplete="name" required /></label><label>Email<input name="email" type="email" placeholder="ola@exemplo.pt" autocomplete="email" required /></label></div><div class="form-row"><label>Idade da criança<select name="age" required><option value="" disabled selected>Selecionar idade</option>${ages.map(([age]) => `<option>${age}${age === 'Famílias' ? '' : ' anos'}</option>`).join('')}</select></label><label>Atividade de interesse<select name="activity" required><option value="" disabled selected>Selecionar atividade</option>${activities.map((a) => `<option>${a.title}</option>`).join('')}<option>Gostava de saber mais</option></select></label></div><label>Mensagem<textarea name="message" rows="3" placeholder="Conte-nos o que gostaria de saber…"></textarea></label><div class="form-submit"><button class="button" type="submit">Enviar pedido ${arrow}</button><p id="form-feedback" aria-live="polite">Demonstração — o formulário ainda não envia dados.</p></div></form></div></section>`; }
function FinalCTA() { return `<section class="final-cta"><div class="section-wrap final-layout"><span class="final-star" aria-hidden="true">✳</span><div><p class="eyebrow">A imaginação não tem pressa</p><h2>Vamos criar uma próxima<br><em>descoberta?</em></h2><p>Quer saber mais sobre as próximas oficinas e experiências da Mini Artistas à Solta?</p></div><div class="final-actions"><a class="button button-dark" href="#contactos">Entrar em contacto ${arrow}</a>${instagramLink('button button-light')}</div></div></section>`; }
function Footer() { return `<footer class="site-footer"><div class="section-wrap footer-main">${logo}<div class="footer-brand-copy"><strong>Mini Artistas à Solta</strong><p>Oficinas criativas em Santarém</p><span>São Vicente do Paul · Santarém</span></div><nav aria-label="Navegação de rodapé"><a href="#inicio">Início</a><a href="#atividades">Atividades</a><a href="#sobre">Sobre</a><a href="#galeria">Galeria</a><a href="#contactos">Contactos</a></nav>${instagramLink('footer-instagram')}</div><div class="section-wrap footer-bottom"><span>© 2026 Mini Artistas à Solta</span><span>Uma demonstração criada pela <b>KOVELO STUDIO</b></span></div></footer>`; }

document.querySelector('#app').innerHTML = `${Navbar()}<main id="main">${Hero()}${ActivityCategories()}${AgeGroups()}${UpcomingActivities()}${WhyCreate()}${Gallery()}${About()}${Location()}${InterestForm()}${FinalCTA()}</main>${Footer()}`;

const menuButton = document.querySelector('.menu-toggle');
const navLinks = document.querySelector('.nav-links');
function closeMenu() { menuButton.setAttribute('aria-expanded', 'false'); menuButton.setAttribute('aria-label', 'Abrir menu'); navLinks.classList.remove('is-open'); document.body.classList.remove('menu-open'); }
menuButton.addEventListener('click', () => { const opening = menuButton.getAttribute('aria-expanded') !== 'true'; menuButton.setAttribute('aria-expanded', String(opening)); menuButton.setAttribute('aria-label', opening ? 'Fechar menu' : 'Abrir menu'); navLinks.classList.toggle('is-open', opening); document.body.classList.toggle('menu-open', opening); });
navLinks.addEventListener('click', (event) => { if (event.target.closest('a')) closeMenu(); });
document.addEventListener('click', (event) => { if (!event.target.closest('.nav-shell') && menuButton.getAttribute('aria-expanded') === 'true') closeMenu(); });
document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeMenu(); });
window.addEventListener('resize', () => { if (window.innerWidth > 760) closeMenu(); });
document.querySelector('#interest-form').addEventListener('submit', (event) => { event.preventDefault(); document.querySelector('#form-feedback').textContent = 'Obrigado pelo interesse! Esta demonstração não envia os dados.'; });

const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: 0.12 });
document.querySelectorAll('.activity-card, .age-row, .experience-card, .value-row, .gallery-item, .about-visual, .interest-form').forEach((element) => { element.classList.add('reveal'); observer.observe(element); });
